use_frameworks!

target 'ios-module-architecture_Example' do
  pod 'ModuleArchitecture', :path => '../'

  target 'ios-module-architecture_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
