use_frameworks!
platform :ios, '10.0'

target 'ios-module-architecture_Example' do
  pod 'ModuleArchitecture', :path => '../'

  target 'ios-module-architecture_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
  end
end
