use_frameworks!
platform :ios, '10.0'

target 'ios-module-architecture_Example' do
  pod 'ModuleArchitecture', :path => '../'

  target 'ios-module-architecture_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
